### ISSUE TITLE
Update Firefox manifests for v68 changes

### ISSUE THREAD

**Issue by bp88** [ProfileCreator/ProfileManifests#103]
Changes are documented here: https://github.com/mozilla/policy-templates/releases/tag/v1.8

This release provides support for the following new policies on Firefox 68 and Firefox ESR 68:

DefaultDownloadDirectory
DownloadDirectory
ExtensionSettings
FirefoxHome
LocalFileLinks
NewTabPage
Preferences
PromptForDownloadLocation
SearchSuggestEnabled

It also makes the following changes to existing policies:

RequestedLocales can now use a string so the value can be blank to use the system locale.
SanitizeOnShutdown has been updated to provide more granular configuration.
SearchEngines has been updated to support POST search engines.

Also the README has been completely updated to provide more detailed information about each policy.

**Comment by WardsParadox** [comment]
Working on this now.

**Comment by apizz** [comment]
Merged
