### ISSUE TITLE
Add OfficeAutoSignIn to com.microsoft.office

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/ProfileManifests#104]
Per https://macadmins.slack.com/archives/C2N7MED7G/p1562834771272700

**Comment by kevinmcox** [comment]
Looks like this preference already exists, but it could use description update to reflect how it influences Outlook.

I'll take care of that as part of my efforts for #116.

**Comment by kevinmcox** [comment]
This is taken care of in #124.
