### ISSUE TITLE
Fix pfm_title for ShowWhatsNewOnLaunch in com.microsoft.office manifest

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/ProfileManifests#105]
Currently, the `pfm_title` for ShowWhatsNewOnLaunch is "Hide what's new message after update".  However, when set to `true` this actually shows what's new on launch messages, rather than hiding them as the `pfm_title` suggests.

Instead, the `pfm_title` should be "**Show** what's new message after update".

**Comment by kevinmcox** [comment]
Fixed in #111.
