### ISSUE TITLE
Fix Skype for Business autoDetectAutoDicoveryURLs key spelling

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/ProfileManifests#108]
Currently is autoDetectAutoDiscoveryURLs ... but Microsoft developers done goofed and it's actually `autoDetectAutoDicoveryURLs`

https://techcommunity.microsoft.com/t5/Skype-for-Business-IT-Pro/Skype-for-Business-Mac-client-Preference-Settings/td-p/66530

**Comment by apizz** [comment]
Should be resolved, but waiting for confirmation before closing.  Thanks for handling, @kevinmcox

**Comment by kevinmcox** [comment]
Sure thing!
