### ISSUE TITLE
Add com.jamf.connect.shares.plist

### ISSUE THREAD

**Issue by qu1gl3s** [ProfileCreator/ProfileManifests#113]
[https://docs.jamf.com/jamf-connect/1.0.0/sync/administrator-guide/File_Shares.html](https://docs.jamf.com/jamf-connect/1.0.0/sync/administrator-guide/File_Shares.html)

All information is located within the Jamf guide provided.

All mappings are the same as the menu.nomad.shares.plist which already exists in ProfileCreator.

**Comment by kevinmcox** [comment]
Is it simply `menu.nomad.shares` pointed at a different preference domain, or are more changes besides just changing the titles and descriptions needed?

**Comment by kevinmcox** [comment]
This has been added in #115.
