### ISSUE TITLE
com.microsoft.office: add new privacy keys for 16.28

### ISSUE THREAD

**Issue by timnottom** [ProfileCreator/ProfileManifests#116]
There are new keys for Office from version 16.28 and up. These are mentioned here: https://macadmins.software/docs/16.28-Privacy-Consent.key
More info here: https://docs.microsoft.com/nl-nl/deployoffice/privacy/mac-privacy-preferences
At time of writing the sheet with all the keys is not updated yet: https://goo.gl/UC04oZ

**Comment by kevinmcox** [comment]
Thanks for filing the issue @timnottom.

**Comment by kevinmcox** [comment]
Also need to update the individual Office application profiles related to the new privacy settings.

While at it, `kSubUIAppCompletedFirstRunSetup1507` needs to be updated as well in the individual app manifests.

**Comment by kevinmcox** [comment]
The main Office manifest has been updated with all the new keys. I'm working on updates for all the individual application manifests now.

**Comment by timnottom** [comment]
Thank you Kevin!
