### ISSUE TITLE
Update com.microsoft.autoupdate.fba to note it no longer applies after Office 16.27

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#117]
The `SendAllTelemetryEnabled` key no longer applies in Office versions after 16.27. There is nothing left to manage in that domain going forward.

Per conversation with @pbowden-msft in Slack: https://macadmins.slack.com/archives/C07UZ1X7B/p1565795925296800

**Comment by apizz** [comment]
@kevinmcox I would say a `pfm_app_max` would do the job here, but a `pfm_note` may be helpful as well.
