### ISSUE TITLE
Update com.microsoft.Office365ServiceV2 to note is no longer applies after 16.24

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#118]
The entire preference domain `com.microsoft.Office365ServiceV2` was removed as of Office 16.24 back in April. There is no reason to manage it for newer releases.

Per conversation with @pbowden-msft in Slack: https://macadmins.slack.com/archives/C07UZ1X7B/p1565795925296800

**Comment by apizz** [comment]
@kevinmcox I would say a `pfm_app_max` should be sufficient

**Comment by kevinmcox** [comment]
Note to self: Got clarification from Paul that this is still used by Office 2016 updates (16.16.x).
