### ISSUE TITLE
Allow Firefox Prompt For Download Location

### ISSUE THREAD

**Issue by BartoX360** [ProfileCreator/ProfileManifests#122]
Hello !
Can you add Prompt For Download Location in Firefox Profile ?
```
<dict>
  <key>PromptForDownloadLocation</key>
  <true/> | <false/>
</dict>
```
Thanks !

**Comment by kevinmcox** [comment]
Documentation is here: https://github.com/mozilla/policy-templates/blob/master/README.md#promptfordownloadlocation

**Comment by kevinmcox** [comment]
@BartoX360 I'm going to open this issue back up so we don't forget it needs to be added.

**Comment by apizz** [comment]
Merged
