### ISSUE TITLE
Add IsKeyExtractable key to the SCEP Profile

### ISSUE THREAD

**Issue by Bretterteig** [ProfileCreator/ProfileManifests#123]
As per Apple's Configuration Profile Reference the SCEP profile does support a boolean key called "IsKeyExtractable" since 10.14.4.

**Comment by kevinmcox** [comment]
Just to clear, we're talking about `KeyIsExtractable` in `com.apple.security.scep` correct?

https://developer.apple.com/documentation/devicemanagement/scep/payloadcontent

**Comment by Bretterteig** [comment]
Yes exactly.
