### ISSUE TITLE
com.microsoft.Edge

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#131]
Now that Microsoft Edge has consolidated on the `com.microsoft.Edge` preference domain for all versions (Canary, Developer and Beta) we should work on adding a manifest for it.

https://docs.microsoft.com/en-us/deployedge/configure-microsoft-edge#configure-microsoft-edge-on-mac

https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies

Since Edge is Chromium based it looks like most, if not all, of the keys are the same as Chrome. So we might be able to re-use that profile as a base to get started.

**Comment by apizz** [comment]
With the release of Microsoft Edge, I initially started by doing what I did for Brave, which is just copying the existing manifest and renaming & updating the applicable items.  However, there are a number of preferences in Edge that are named differently than their Chrome counterpart (BookmarksBarEnabled vs FavoritesBarEnabled) and others that just don't exist.

There's a full Edge manifest within Edge at `Microsoft Edge.app/Contents/Resources/com.microsoft.edgemac.manifest/Contents/Resources/com.microsoft.edgemac.manifest`

In my upcoming PR, I've updated the documentation URLs for everything that's listed on the Microsoft docs as of this moment and plan on commenting everything else out.

I'll take another pass at some point to go through and add all the Edge-specific preferences, but at least this way it's at least mostly usable.
