### ISSUE TITLE
Add AppleEnableSwipeNavigateWithScroll to com.google.Chrome.plist

### ISSUE THREAD

**Issue by jaykepeters** [ProfileCreator/ProfileManifests#132]
Domain: com.google.Chrome
Key: AppleEnableSwipeNavigateWithScrolls
Type: Boolean

**Comment by kevinmcox** [comment]
Looks like it needs an "s" at the end, `AppleEnableSwipeNavigateWithScrolls`.

It also looks like `AppleEnableMouseSwipeNavigateWithScrolls` does the same thing for the Magic Mouse.

**Comment by jaykepeters** [comment]
> Looks like it needs an "s" at the end, `AppleEnableSwipeNavigateWithScrolls`.
> 
> It also looks like `AppleEnableMouseSwipeNavigateWithScrolls` does the same thing for the Magic Mouse.

Thanks! Added!

**Comment by apizz** [comment]
Is this still an issue?  I don't see any chrome preferences involving `AppleEnableSwipeNavigateWithScrolls` ...

**Comment by apizz** [comment]
Still no documentation listed for `AppleEnableSwipeNavigateWithScrolls`, so closing.
