### ISSUE TITLE
com.microsoft.wdav

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#135]
Microsoft Defender ATP has manageable preferences as documented at this page:

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/microsoft-defender-atp-mac-preferences

**Comment by apizz** [comment]
Maybe we'll get Gatekeeper on Windows? 😆

**Comment by apizz** [comment]
I just started trying to create this manifest.  This is by far the worst profile formatting I've ever seen.

**Comment by apizz** [comment]
Addressed in #240
