### ISSUE TITLE
ManifestsApple / com.apple.TCC.configuration-profile-policy.plist incomplete

### ISSUE THREAD

**Issue by Headbolt** [ProfileCreator/ProfileManifests#143]
There is a new section as of Catalina Beta 6 called "Screen Recording" (in the GUI) nobody seem to have any documentation of this and profiles for it will be quite important.

**Comment by bp88** [comment]
https://developer.apple.com/documentation/devicemanagement/privacypreferencespolicycontrol/services

You're referring to the following preference:
ScreenCapture

You can only deny it with a profile it looks like so if you had any hope of allowing it for specific apps I'm not sure you'll be able to.

**Comment by Headbolt** [comment]
Thats Just dumb !!!

So our Corporate Remote Access/Remote Support solution, which defaults to unticked, can only be allowed by an Administrator unlocking the panel and allowing it !!!

Our systems are 85% remote, so we have no way of ticking the box after upgrade without actually talking a user through it AND giving them an Admin password, that cant be acceptable in an Enterprise.

Add to that the fact that it also breaks Docks for MacBooks by the same mechanism.

The GUI defines it as Screen Recording from Beta 6 onwards.

![image](https://user-images.githubusercontent.com/54707369/64022429-18695080-cb2e-11e9-8650-42b2adb5c930.png)

**Comment by bp88** [comment]
You'd want to provide Apple that feedback. Join AppleSeed if possible and give them feedback!
