### ISSUE TITLE
New keys in Apple Configurator 2.10

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#158]
These additional options were just added to Apple Configurator 2.10.

We need to check if we already support these or if they need to be added.

> iOS
> • Wi-Fi: Configure WPA3 Personal security type
> • VPN IKEv2: Configure Enable Fallback setting to support Wi-Fi Assist
> • Exchange ActiveSync: Enable Mail, Calendar, Contacts, and Reminders individually for managed accounts
> • Configure new supervised-only Restrictions: Allow Find My Device, Allow Find My Friends, Allow external drive access in Files app, Force Wi-Fi to on
> • Skip Dark Mode and Welcome panes in Setup Assistant
> 
> tvOS
> • Wi-Fi: Configure WPA3 Personal security type

**Comment by apizz** [comment]
Wifi addressed in #204

**Comment by apizz** [comment]
New iOS restrictions prefs addressed in #205

**Comment by apizz** [comment]
Exchange activesync prefs addressed in #206

**Comment by apizz** [comment]
Don't see anything on the Setup Assignment for Dark Mode and Welcome panes in the documentation.  To you have those preferences somewhere, @kevinmcox ?

**Comment by kevinmcox** [comment]
I don't and actually do not even see those as options in Configurator. The content of my issue was directly from the release notes in the App Store.

**Comment by apizz** [comment]
I revisited this and did a full search of Apple Configurators manifests and could not find anything for "Dark", "Dark Mode", "Welcome", or "Setup Assistant".  Given this, I'm going to mark this issue as closed.
