### ISSUE TITLE
Cannot enable fast user switching

### ISSUE THREAD

**Issue by aboak0119** [ProfileCreator/ProfileManifests#159]
There does not appear to be any option to enable fast user switching (located in System Preferences -> Users and Groups -> Login Options) from the "Login Window" option selection of ProfileCreator.

**Comment by kevinmcox** [comment]
@aboak0119 That option is under the Global Preferences payload. It is under the second set of preferences, the Apple logo.

**Comment by aboak0119** [comment]
Thank you so much!
