### ISSUE TITLE
New Find My Mac settings for Catalina

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#164]
These were posted in the #catalina channel in Slack:

**com.apple.icloud.managed**
```
<key>DisableFMMiCloudSetting</key>
<true/>
```
that will mimic the 10.14.6 behavior so if someone is logged into it, it will just be grayed out

**com.apple.applicationaccess**
```
<key>allowFindMyDevice</key>
<false/>
<key>allowFindMyFriends</key>
<false/>

```
will lock down the actual app so you cant share

**Comment by apizz** [comment]
We don't yet have a `com.apple.icloud.managed` manifest, so going to hold off on that piece of this for now.  I wish Apple would just document this stuff ...

**Comment by apizz** [comment]
New com.apple.icloud.managed manifest added with icon.  Please quit and reopen ProfileCreator to get the latest manifests.
