### ISSUE TITLE
Add System Extensions Payload

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/ProfileManifests#173]
Will ultimately replace Approved Kernel Extensions payload

macOS 10.15+

`AllowUserOverrides` - Allow users to approve system extensions
`AllowedSystemExtensionTypes` - Allowed System Extension Types: 
- Allowed System Extensions
- Allowed System Extension Types
- Allowed Team Identifiers

`AllowedSystemExtensions` - Allowed System Extensions
`AllowedTeamIdentifiers` - Allowed Team Identifier

**Comment by apizz** [comment]
I'm not sure how to accomplish this with the current developmental state of ProfileCreator ... We have manifests that allow you to specify both a custom key and value (ex. Jamf Connect) ...
```
<key>pfm_name</key>
<string>KeychainItems</string>
<key>pfm_subkeys</key>
<array>
	<dict>
		<key>pfm_name</key>
		<string>{{key}}</string>
		<key>pfm_title</key>
		<string>Keychain Item</string>
		<key>pfm_type</key>
		<string>string</string>
		<key>pfm_value_placeholder</key>
		<string>Exchange</string>
	</dict>
	<dict>
		<key>pfm_name</key>
		<string>{{value}}</string>
		<key>pfm_title</key>
		<string>Account</string>
		<key>pfm_type</key>
		<string>string</string>
		<key>pfm_value_placeholder</key>
		<string>&lt;&lt;shortname&gt;&gt;@&lt;&lt;domain&gt;&gt;.onmicrosoft.com</string>
	</dict>
</array>
```
... the end result which has an array of dictionaries:
![Screen Shot 2020-01-07 at 2 27 29 PM](https://user-images.githubusercontent.com/11789931/71922893-db573f80-3159-11ea-8932-90c448bb7fc4.png)

However, it does not appear that as things are that there's a way to have an array of strings with a custom entered key for the array within a dictionary.  The XML below is from an MDM payload where `test2` is a user-provided Team Identifier and the strings within are the only 3 possible system extension types (documentation here: https://developer.apple.com/documentation/devicemanagement/systemextensions) and `test3` is a user-provided Team Identifier key for an array of strings, which are user-provided identifiers for the individual extensions:
```
<key>AllowedSystemExtensionTypes</key>
<dict>
	<key>test2</key>
	<array>
		<string>DriverExtension</string>
		<string>EndpointSecurityExtension</string>
		<string>NetworkExtension</string>
	</array>
</dict>
<key>AllowedSystemExtensions</key>
<dict>
	<key>test3</key>
	<array>
		<string>test</string>
	</array>
</dict>
```
I can get close, but I can't get to the point where we can choose the desired string options.  Manifest XML & image:
```
<array>
	<dict>
		<key>pfm_name</key>
		<string>{{key}}</string>
		<key>pfm_title</key>
		<string>Team Identifier</string>
		<key>pfm_type</key>
		<string>string</string>
	</dict>
	<dict>
		<key>pfm_name</key>
		<string>{{value}}</string>
		<key>pfm_subkeys</key>
		<array>
			<dict>
				<key>pfm_name</key>
				<string>{{value}}</string>
				<key>pfm_description</key>
				<string></string>
				<key>pfm_range_list</key>
				<array>
					<string>DriverExtension</string>
					<string>EndpointSecurityExtension</string>
					<string>NetworkExtension</string>
				</array>
				<key>pfm_range_titles</key>
				<array>
					<string>Driver Extension</string>
					<string>Endpoint Security Extension</string>
					<string>Network Extension</string>
				</array>
				<key>pfm_title</key>
				<string>Allowed System Extension Types</string>
				<key>pfm_type</key>
				<string>string</string>
			</dict>
		</array>
		<key>pfm_title</key>
		<string>TEST</string>
		<key>pfm_type</key>
		<string>array</string>
	</dict>
</array>
```
![Screen Shot 2020-01-07 at 2 44 37 PM](https://user-images.githubusercontent.com/11789931/71924064-40139980-315c-11ea-88a5-6d258b72e64d.png)

As such, outside of someone taking on the ProfileCreator app, I think this would have to be template we supply outside of ProfileCreator ... that being said this payload requires you to have a User-Approved MDM, so the need to build this outside of ProfileCreator is perhaps not so critical ...

**Comment by relgit** [comment]
@apizz I've just submitted PR #427 which resolves the titular issue by adding the System Extension Policy manifest, however it doesn't address the other issue discussed in the comments, of ProfileCreator not fully supporting the manifest.

If you or others are interested in continuing the discussion about possible workarounds like a template then lets open a separate issue here on this repository. Otherwise I think that it would be better to open a specific issue for adding support on the PC repository.
