### ISSUE TITLE
Update Firefox for new preferences added in v69 and v70

### ISSUE THREAD

**Issue by bp88** [ProfileCreator/ProfileManifests#176]
See the release notes here: https://github.com/mozilla/policy-templates/releases

May also want to inquire about the following preferences in the #firefox channel on Slack as I believe these settings can also be set as well but are not currently documented:
http://kb.mozillazine.org/App.update.auto
See the "Related Preferences" section:

- app.update.enabled
- app.update.auto
- app.update.mode
- app.update.interval
- app.update.silent
- app.update.download.backgroundInterval
- app.update.incompatible.mode
- app.update.promptWaitTime
- app.update.nagTimer.restart
- app.update.idletime

**Comment by bp88** [comment]
Disregard the related preferences section in http://kb.mozillazine.org/App.update.auto. Confirmed with Mike Kaply that those are not manageable via profile yet. See: https://macadmins.slack.com/archives/C5ACP4TUZ/p1572274839069700

The rest of request still stands.

**Comment by apizz** [comment]
Thanks and sorry for the delay on this.  Will work on getting this done as soon as I can.

**Comment by apizz** [comment]
I'm now working on these.  Hope to have a PR ready by end of this week

**Comment by apizz** [comment]
Please quit ProfileCreator and reopen to get the latest Firefox manifest
