### ISSUE TITLE
com.google.Chrome.plist needs keys for Legacy SameSite cookie behavior settings

### ISSUE THREAD

**Issue by everetteallen** [ProfileCreator/ProfileManifests#220]
Not sure who would maintain these plists but com.google.Chrome.plist could use a complete set of keys for the Legacy SameSite cookie behavior settings group of Chrome Policies.  Recently the issue of Cross Site Cookie enforcement for Chrome 80.xx and beyond has made management of this group of preferences more important.  
See:
https://www.jamf.com/jamf-nation/discussions/34522/manage-chrome-settings-legacysamesitecookiebehaviorenabled
and
https://cloud.google.com/docs/chrome-enterprise/policies/?policy=LegacySameSiteCookieBehaviorEnabledForDomainList
Thanks!

**Comment by apizz** [comment]
@everetteallen please quit & reopen ProfileCreator to get the latest Chrome manifest with these added preferences

**Comment by everetteallen** [comment]
@apizz Confirmed Thank you!
