### ISSUE TITLE
wired settings

### ISSUE THREAD

**Issue by a-dorofeev** [ProfileCreator/ProfileManifests#231]
HELLO! 
I can’t find the settings for the wired network of the Mac OS. I need to create a payload for 802.1x (authorization on network before user's login in system Mac OS)

**Comment by apizz** [comment]
Hasn't been added yet.  Will work on this when I have time.

**Comment by apizz** [comment]
@a-dorofeev, please quit and reopen ProfileCreator to find the added 802.11x manifests

![Screen Shot 2020-04-11 at 12 21 51 PM](https://user-images.githubusercontent.com/11789931/79049025-15b7f900-7bef-11ea-8ebb-1a8db9aa4a58.png)

If you notice any discrepancies or problems, please file another issue.
