### ISSUE TITLE
Update Firefox for new preferences added in v73, v74, and v75

### ISSUE THREAD

**Issue by bp88** [ProfileCreator/ProfileManifests#252]
### Please provide the following information:

**Name of App / Payload**: Firefox

**Preference key(s) to be added / updated**:
The v73 release updates the following policies:
[DisplayMenuBar](https://github.com/mozilla/policy-templates/blob/master/README.md#displaymenubar) - Added additional options for always on or always off.
[EnableTrackingProtection](https://github.com/mozilla/policy-templates/blob/master/README.md#enabletrackingprotection) - Exceptions added

It adds the following preferences to the [Preferences](https://github.com/mozilla/policy-templates/blob/master/README.md#preferences) policy.
> dom.xmldocument.load.enabled (Firefox ESR 68 only)
> dom.xmldocument.async.enabled  (Firefox ESR 68 only)

It removes the following preferences from the [Preferences](https://github.com/mozilla/policy-templates/blob/master/README.md#preferences) policy.
> browser.cache.disk.parent_directory (Wasn't working correctly)

The v74 release updates the following policies:
[Permissions](https://github.com/mozilla/policy-templates/blob/master/README.md#permissions) - Added support for Autoplay.
[SanitizeOnShutdown](https://github.com/mozilla/policy-templates/blob/master/README.md#sanitizeonshutdown) - Added support for Locked and moved the GPO to a category for more flexibility.

The Tracking Protection GPO was also moved to a category for more flexibility.

Th v75 release provides support for the following new policies:
[AppAutoUpdate](https://github.com/mozilla/policy-templates/blob/master/README.md#appautoupdate) (should be used instead of app.update.auto in Preferences)
[DisableDefaultBrowserAgent](https://github.com/mozilla/policy-templates/blob/master/README.md#disabledefaultbrowseragent)
[UserMessaging](https://github.com/mozilla/policy-templates/blob/master/README.md#usermessaging)

The v75 release updates the following policies:
[DNSOverHTTPS](https://github.com/mozilla/policy-templates/blob/master/README.md#dnsoverhttps) - Added support for ExcludedDomains. Also moved the GPO to a category for more flexibility.

**Applicable Preference Documentation URL(s)**:
See the release notes here: https://github.com/mozilla/policy-templates/releases

**Comment by apizz** [comment]
`DisplayMenuBar` & `EnableTrackingProtection` were added in a previous commit: https://github.com/ProfileCreator/ProfileManifests/commit/dd5a081dc2fb3f0b2a862fdbef0917c90a183818

Adding preferences and additional options per the docs.

**Comment by apizz** [comment]
`DisableDefaultBrowserAgent` appears to be Windows-only, so not including here.

**Comment by apizz** [comment]
Please quit & reopen ProfileCreator to see the added preferences.
