### ISSUE TITLE
Add new preference to disable VBA for MS Office

### ISSUE THREAD

**Issue by bp88** [ProfileCreator/ProfileManifests#285]
### Please provide the following information:

**Name of App / Payload**: com.microsoft.office

**Preference key(s) to be added / updated**: VisualBasicEntirelyDisabled
**Type**: Bool

**Applicable Preference Documentation URL(s)**: https://macadmins.software/matrix/

**Notes**: This is a preference key that was introduced in 16.32 that will completely disable VBA. It effects the 3 Office apps: Excel, PowerPoint, Word.

**Comment by apizz** [comment]
Thanks, @bp88.  This has been added in #286.  Please quit and reopen PC to get the latest manifests.
