### ISSUE TITLE
Improve the com.apple.dock manifest

### ISSUE THREAD

**Issue by relgit** [ProfileCreator/ProfileManifests#295]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*
com.apple.dock

**Preference key(s) needing fixing**: *ex. `AppUpdateURL`*
`static-apps`, `static-others`

**Description of problem(s) / error(s) with listed key(s)**: *ex. When `X` preference is configured, it does not *
Tables contains superfluous columns, field range items are wrong or missing, tables should be the same for both fields

**Description of expected behavior**:
Should align to documentation

**Applicable Documentation URL(s)**: *If applicable ...*
https://developer.apple.com/documentation/devicemanagement/dock

**How are you testing / deploying your profile?**: *ex. manual profile install, MDM, etc.*
N/A

**Comment by kevinmcox** [comment]
Is this still an outstanding issue? I know there have been a handful of changes to the Dock manifest since it was opened.

**Comment by relgit** [comment]
Yes, I'm afraid most of the work we've done on it was generic, like changing `pfm_required` to `pfm_require`, adding default values, and such - part of wider work across multiple manifests. Nothing addressing the issues that I'd described.
