### ISSUE TITLE
Add Google Drive File Stream manifest

### ISSUE THREAD

**Issue by flammable** [ProfileCreator/ProfileManifests#307]
### Please provide the following information:

**App Name**: Google Drive File Stream

**App URL**: https://support.google.com/a/answer/7491144

**App Profile Documentation URL**: https://support.google.com/a/answer/7644837?hl=enbn

**Payload / Domain**: com.google.drivefs.settings

**Comment by apizz** [comment]
woohoo!  I was waiting for Google to implement this ...

**Comment by flammable** [comment]
I found it while troubleshooting why the `content_cache` folder is so large - it turns out that you can't control the cache size via the GUI, only via the preferences file. By default, it can use up to 20% of your total disk space. 😳

**Comment by apizz** [comment]
You can quit and reopen PC to see Google File Stream

**Comment by flammable** [comment]
Thank you!
