### ISSUE TITLE
Fix Big Sur pfm_macos_min version in manifests

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/ProfileManifests#319]
### Please provide the following information:

**Name of App / Payload**: Several

**Preference key(s) needing fixing**: Those preferences and payloads recently added & updated for macOS Big Sur which are reflected by pfm_macos_min `10.16`.

**Description of problem(s) / error(s) with listed key(s)**: While originally entered as `10.16`, in Big Sur betas it appears that Apple will in fact use 11.0.  Not critical ATM, but should be addressed.

**Description of expected behavior**: pfm_macos_min values of new prefs should be `11.0` instead of `10.16`

**Applicable Documentation URL(s)**: N/A

**How are you testing / deploying your profile?**: N/A

**Comment by kevinmcox** [comment]
It looks like this was addressed with #387. I can't find any usage of 10.16 in the manifests at this point.

**Comment by apizz** [comment]
Thanks, @kevinmcox
