### ISSUE TITLE
Please add forceDelayedAppSoftwareUpdates key to macOS Restrictions -> Software Updates

### ISSUE THREAD

**Issue by Coros** [ProfileCreator/ProfileManifests#376]
### Please provide the following information:

**App Name**: *macOS Software Updates*

**App Profile Documentation URL**: *https://developer.apple.com/documentation/devicemanagement/restrictions*

**Payload / Domain**: *com.apple.applicationaccess*

Key: forceDelayedAppSoftwareUpdates

If true, delays user visibility of non-OS Software Updates. Requires a supervised device.
Visibility of Operating System updates is controlled through forceDelayedSoftwareUpdates.

The delay is 30 days unless enforcedSoftwareUpdateDelay is set to another value.

Available in macOS 11 and later.

Default: false

**Comment by apizz** [comment]
Thanks for this.  Will get this added as soon as I (or someone else) is able.
