### ISSUE TITLE
Update Chrome deprectated keys

### ISSUE THREAD

**Issue by Bretterteig** [ProfileCreator/ProfileManifests#379]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*
com.google.chrome

**Preference key(s) to be added / updated**: *ex. `AppUpdateURL`, `Bookmarks`, etc.*
Deprecated:
AuthNegotiateDelegateWhitelist
AuthServerWhitelist

Replaced by: 
AuthNegotiateDelegateAllowlist

**Applicable Preference Documentation URL(s)**:
https://cloud.google.com/docs/chrome-enterprise/policies/?policy=AuthNegotiateDelegateWhitelist
https://cloud.google.com/docs/chrome-enterprise/policies/?policy=AuthServerWhitelist
https://cloud.google.com/docs/chrome-enterprise/policies/?policy=AuthNegotiateDelegateAllowlist

**Comment by apizz** [comment]
Thanks for this.  There are a number of additional related blacklist/whitelist changes with other preferences that I'm including in the PR I'm working on to address this.
