### ISSUE TITLE
Add "com.apple.Safari.SandboxBroker" Domain

### ISSUE THREAD

**Issue by walkintom** [ProfileCreator/ProfileManifests#382]
App Name: Safari (macOS 10.14+)

Domain: com.apple.Safari.SandboxBroker

Payload: ShowDevelopMenu
Type: Boolean

The "ShowDevelopMenu" key is now necessary for macOS 10.14/Safari 14 and above to successfully prevent the Develop menu from being enabled in Preferences -> Advanced -> Show Develop menu in menu bar.

**Comment by apizz** [comment]
Just to be clear, does this mean that for macOS 10.14+ running Safari 14+ that the existing `IncludeDevelopMenu` key does not work and therefore should be listed as deprecated?

**Comment by walkintom** [comment]
That’s correct, I guess marking the key in that payload as deprecated makes sense.
