### ISSUE TITLE
PFM Review / pfm_require inconsistency

### ISSUE THREAD

**Issue by ygini** [ProfileCreator/ProfileManifests#396]
Based on the wiki, `pfm_require` is supposed to be a string with support for values like `always` or `push`.

Right now, there is 15 occurence of this key set with the boolean value `true`.

A general cleanup to match the pfm specification is required.

The 15 occurrences are in:
- ./ManagedPreferencesApplications/com.brave.Browser.plist
- ./ManagedPreferencesApplications/com.google.Chrome.plist
- ./ManagedPreferencesApplications/com.jamf.connect.sync.plist
- ./ManagedPreferencesApplications/com.microsoft.Edge.plist
- ./ManagedPreferencesApplications/org.mozilla.firefox.plist
- ./ManifestsApple/com.apple.AIM.account.plist
- ./ManifestsApple/com.apple.Dictionary.plist
- ./ManifestsApple/com.apple.carddav.account.plist
- ./ManifestsApple/com.apple.eas.account.plist
- ./ManifestsApple/com.apple.google-oauth.plist
- ./ManifestsApple/com.apple.jabber.account.plist

**Comment by relgit** [comment]
Thanks for reporting this @ygini.

Looks like a mistake in the manifests, though I could only find this issue in four of the manifests that you listed (perhaps the keys __pfm_require__ and __pfm_required__ got conflated? The latter is defined as a boolean key so the value is correct).

Here are the manifests where I did find the issue:
com.apple.Dictionary
com.apple.jabber.account
com.apple.AIM.account
com.jamf.connect.sync

Are you interested in submitting a PR correcting this?

**Comment by homebysix** [comment]
Looks like these have all been fixed, most recently in this PR: https://github.com/ProfileCreator/ProfileManifests/pull/468

**Comment by relgit** [comment]
Indeed.
