### ISSUE TITLE
PFM Review / Invalid usage of subkeys for array

### ISSUE THREAD

**Issue by ygini** [ProfileCreator/ProfileManifests#401]
Hello

For most (all?) object type `array` in the manifests, there is an invalid usage of `pfm_subkeys`.

In the context of `array` type, `pfm_subkeys` are used to provide list of valid subkeys to add to the array.

However, those subkeys are invalid because of the lack of `pfm_name`. 

`pfm_name` is used to represent the key of the value in a dictionary, so indeed it's not needed for an array, but still the pfm format require this key. And this key can be used in other situation for condition check for example.

In original MCX system, array subkeys was always providing a `pfm_name` even if not used in the final preferences.

It's mandatory to edit all manifests to fix this and stick to the original manifest behavior.

A good practice to name this key is to use the singular form of the related array key. For example, using `SHKDeniedShareService` when the array key is `SHKDeniedShareServices`.

During this review, it's also mandatory to check each of the array subkey to be sure that `pfm_require` and `pfm_unique` are properly set.

This remark apply for:
- `com.apple.applicationaccess-iOS` / `pfm_subkeys` / Item 117
- `com.apple.applicationaccess-iOS` / `pfm_subkeys` / Item 118
- `com.apple.xsan.preferences` / `pfm_subkeys` / Item 8
- `com.apple.xsan.preferences` / `pfm_subkeys` / Item 9
- `com.apple.xsan.preferences` / `pfm_subkeys` / Item 10
- `com.apple.xsan.preferences` / `pfm_subkeys` / Item 11
- `com.apple.AssetCache.managed` / `pfm_subkeys` / Item 54 / `pfm_subkeys` / Item 0
- `com.apple.dnsSettings.managed` / `pfm_subkeys` / Item 7 / `pfm_subkeys` / Item 1 / `pfm_subkeys` / Item 0
- `com.apple.dnsSettings.managed` / `pfm_subkeys` / Item 7 / `pfm_subkeys` / Item 4 / `pfm_subkeys` / Item 0
- `com.apple.dnsSettings.managed` / `pfm_subkeys` / Item 8 / `pfm_subkeys` / Item 1 / `pfm_subkeys` / Item 1 / `pfm_subkeys` / Item 0
- `com.apple.dnsSettings.managed` / `pfm_subkeys` / Item 8 / `pfm_subkeys` / Item 2 / `pfm_subkeys` / Item 0
- `com.apple.dnsSettings.managed` / `pfm_subkeys` / Item 8 / `pfm_subkeys` / Item 3 / `pfm_subkeys` / Item 0
- `com.apple.dnsSettings.managed` / `pfm_subkeys` / Item 8 / `pfm_subkeys` / Item 5 / `pfm_subkeys` / Item 0
- `com.apple.security.certificatetransparency` / `pfm_subkeys` / Item 7 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 10 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 10 / `pfm_subkeys` / Item 0 / `pfm_subkeys` / Item 5 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 10 / `pfm_subkeys` / Item 0 / `pfm_subkeys` / Item 6 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 10 / `pfm_subkeys` / Item 0 / `pfm_subkeys` / Item 7 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 11 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 12 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 13 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 16 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 16 / `pfm_subkeys` / Item 0 / `pfm_subkeys` / Item 1 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 17 / `pfm_subkeys` / Item 0
- `com.apple.education` / `pfm_subkeys` / Item 17 / `pfm_subkeys` / Item 0 / `pfm_subkeys` / Item 2 / `pfm_subkeys` / Item 0
- `com.apple.ShareKitHelper` / `pfm_subkeys` / Item 7 / `pfm_subkeys` / Item 0
- `com.apple.ShareKitHelper` / `pfm_subkeys` / Item 8 / `pfm_subkeys` / Item 0
- `com.apple.networkusagerules` / `pfm_subkeys` / Item 8 / `pfm_subkeys` / Item 0
- `com.apple.networkusagerules` / `pfm_subkeys` / Item 8 / `pfm_subkeys` / Item 0 / `pfm_subkeys` / Item 0 / `pfm_subkeys` / Item 0
- `com.apple.SetupAssistant.managed` / `pfm_subkeys` / Item 15 / `pfm_subkeys` / Item 0
- `com.apple.webcontent-filter` / `pfm_subkeys` / Item 10 / `pfm_subkeys` / Item 0
- `com.apple.webcontent-filter` / `pfm_subkeys` / Item 12 / `pfm_subkeys` / Item 0
- `com.apple.webcontent-filter` / `pfm_subkeys` / Item 13 / `pfm_subkeys` / Item 0
- `com.apple.applicationaccess-tvOS` / `pfm_subkeys` / Item 10 / `pfm_subkeys` / Item 0
- `com.apple.applicationaccess-tvOS` / `pfm_subkeys` / Item 11 / `pfm_subkeys` / Item 0

**Comment by relgit** [comment]
Thank you for this deep-dive @ygini.

The PFM specs do not always require the `pfm_name` key. Here's what they say about it:

> Specifies the name of a preference key. This key is required for all keys except the subkeys of an array.

(https://developer.apple.com/library/archive/documentation/MacOSXServer/Conceptual/Preference_Manifest_Files/Chapter_1/PM_Chapter1.html)

You're providing condition checks as an example for a situation where this is necessary. Could you provide more details?

**Comment by ygini** [comment]
So the original Apple format is in contradiction with what is written in the repository documentation here https://github.com/ProfileCreator/ProfileManifests/wiki/Manifest-Format#manifest-format and for what I've seen in original MCX shipped with 10.6.

Regarding condition check, to be able to target the key with a `pfm_target`.

From a purely data centric perspective, having this key mandatory everywhere except if nested in an array is a bit odd I would say. When it's time to check information coherence it mean additional checks but I can deal with it if it's wanted.

I guess there is two options now:
- updating the wiki to a more accurate description for this key
- making this key mandatory everywhere

Both option are valid to me as long as it's explicit

**Comment by relgit** [comment]
I think that it's better to stick with the first option and to treat `pfm_name` similarly to Apple for now. It also makes it easier to contribute manifests to the repository.

Another reason is that array items are conventionally referred to by index. Arrays do not natively support KVC paths to their items anyway (whether by name or by index), so if any custom logic is developed for condition checks it can default to using indexes.

It's definitely a good idea to clear this up in the wiki, and I just went ahead and did that - thanks!

I believe this settles this issue so I'm going to go ahead and close it.
