### ISSUE TITLE
Problem exporting Firefox-Profile

### ISSUE THREAD

**Issue by tkriener** [ProfileCreator/ProfileManifests#413]
**Name of App / Payload**: Firefox

**Preference key(s) needing fixing**: `Title`

**Description of problem(s) / error(s) with listed key(s)**:  Invalid value for key: Title in payload domain: org.mozilla.firefox of type: managedPreferencesApplications

**Description of expected behavior**:

If I try to export a Profile with Firefox-Settings I get the Error, that the value for the key `Title` is invalid.
Exporting an minimum Profile with just `Enable Enterprise Policies` works, so it seems there is something wrong in my settings.
Do you have any hints how to find the problem?

**How are you testing / deploying your profile?**: MDM

**Comment by tkriener** [comment]
Found it, it was an empty Bookmark...

**Comment by apizz** [comment]
@tkriener good find.  Yeah those messages are helpful in that they usually identify a problem, but not always as clearly as they might what the actual problem is.
