### ISSUE TITLE
Add SupportApp Manifest

### ISSUE THREAD

**Issue by marklajer** [ProfileCreator/ProfileManifests#414]
### Please provide the following information:

**App Name**: *SupportApp*

**App URL**: *https://github.com/root3nl/SupportApp/*

**App Profile Documentation URL**: https://github.com/root3nl/SupportApp/#configuration

**Payload / Domain**: *nl.root3.support.plist*

**Comment by apizz** [comment]
@marklajer please quit & reopen ProfileCreator to get the latest manifests, including this one.  Whenever you create your profile, please test it and make sure it achieves the desired result.

Thanks for filing the issue!
