### ISSUE TITLE
edu.psu.macoslaps.plist

### ISSUE THREAD

**Issue by dechkovanen** [ProfileCreator/ProfileManifests#426]
### Please provide the following information:

**Name of App / Payload**: edu.psu.macoslaps.plist

**Preference key(s) to be added / updated**: ADD: Method; dropdown with choices "AD" (default) and "Local"

**Applicable Preference Documentation URL(s)**: https://github.com/joshua-d-miller/macOSLAPS/releases/tag/2.0.0(687)

**Comment by apizz** [comment]
Addressed in #446
