### ISSUE TITLE
WWDC 2021 New iOS & iPadOS Keys

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/ProfileManifests#439]
### Please provide the following information:

**Name of App / Payload**: Several

**Preference key(s) to be added / updated**: Several

**Applicable Preference Documentation URL(s)**:

![Screen Shot 2021-06-14 at 9 27 21 AM](https://user-images.githubusercontent.com/11789931/121899897-d6090780-ccf2-11eb-8312-5bef32c961fd.png)

**Comment by relgit** [comment]
@apizz, a quick note if you're getting started on this that I have an updated MDM manifest PR coming up, off of which it would make more sense to work, and that most of the inclusivity changes were already made in iOS 14.5, so they are currently implemented in #436.

I'll come back and update here as soon as the MDM PR is ready.

**Comment by apizz** [comment]
Sounds good, ty. Was more interested in the macOS side of things so was planning on tackling that soonish. My own lack of interaction with Big Sur has delayed things and that's not ok 😅

**Comment by relgit** [comment]
The MDM PR (#442) is now live.
