### ISSUE TITLE
com.apple.mcxprinting

### ISSUE THREAD

**Issue by c-orlik** [ProfileCreator/ProfileManifests#456]
### Please provide the following information:

**Name of App / Payload**: com.apple.airprint

**Preference key(s) to be added / updated**: RequireAdminToAddPrinters

**Applicable Preference Documentation URL(s)**: https://developer.apple.com/documentation/devicemanagement/printing https://support.apple.com/en-gb/guide/mdm/mdm9514788c/web

**Comment by kevinmcox** [comment]
Looks like this key is under `com.apple.mcxprinting` not `com.apple.airprint`.

**Comment by apizz** [comment]
@kevinmcox I see you self assigned this.  Lmk if you want 👀

**Comment by kevinmcox** [comment]
@apizz It is all done except for that one key I asked about in Slack last week, I just need look at your response and revisit.

**Comment by apizz** [comment]
Addressed in #522
