### ISSUE TITLE
Add missing keys to the Restrictions manifest

### ISSUE THREAD

**Issue by relgit** [ProfileCreator/ProfileManifests#458]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*
Restrictions (sepcifically `com.apple.applicationaccess-macOS.plist`)

**Preference key(s) needing fixing**: *ex. `AppUpdateURL`*
`forceDelayedMajorSoftwareUpdates`
`enforcedSoftwareUpdateMajorOSDeferredInstallDelay`
`enforcedSoftwareUpdateMinorOSDeferredInstallDelay`
`enforcedSoftwareUpdateNonOSDeferredInstallDelay`

**Description of problem(s) / error(s) with listed key(s)**: *ex. When `X` preference is configured, it does not *
Keys missing

**Description of expected behavior**:
N/A

**Applicable Documentation URL(s)**: *If applicable ...*
https://developer.apple.com/documentation/devicemanagement/restrictions

**How are you testing / deploying your profile?**: *ex. manual profile install, MDM, etc.*
N/A

**Comment by apizz** [comment]
Addressed in #460
