### ISSUE TITLE
Add BBEdit keys for version 14 licensing & organization

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/ProfileManifests#459]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*

**Preference key(s) to be added / updated**: *ex. `AppUpdateURL`, `Bookmarks`, etc.*

**Applicable Preference Documentation URL(s)**:

**Comment by macprince** [comment]
Licensing keys for BBEdit 14 are already present, from my pull requests #454 and #455 back in July.
