### ISSUE TITLE
Forcepoint Preference Pane

### ISSUE THREAD

**Issue by csvjamfteam** [ProfileCreator/ProfileManifests#464]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*

**Preference key(s) to be added / updated**: *ex. `AppUpdateURL`, `Bookmarks`, etc.*

**Applicable Preference Documentation URL(s)**:

**Comment by csvjamfteam** [comment]
Hi, sorry, i missed that info.
the official website is https://www.forcepoint.com/
about bundle ID, might be a bit of a problem there, the app uas more than one component
com.websense.endpoint.helper
com.forcepoint.ep.ESDaemonBundle
both of them have the same certificate leaf[subject.OU] = C489D5E8E8
Hope this is what you need

**Comment by apizz** [comment]
So I should have been more explicit, what is the `CFBundleIdentifier` of the Forcepoint preference pane?  This is what's important for the profile, not the actual software application.

Example for the Battery.prefPane on Big Sur:

```
defaults read /System/Library/PreferencePanes/Battery.prefPane/Contents/Info.plist CFBundleIdentifier            15:38:43
com.apple.preference.battery
```

**Comment by apizz** [comment]
This is documented here: https://github.com/ProfileCreator/ProfileCreator/wiki/System-Preferences

**Comment by csvjamfteam** [comment]
Hi

SOrry, i missed that piece of info.
Thank you for the time and help!
Best Regards

*Adrian Guliciuc*
*Senior IT Technical Support, **IT **Department*

The content of this communication is classified as Softvision Confidential
and Proprietary Information

**Comment by apizz** [comment]
Ok just provide that info when you're able

**Comment by csvjamfteam** [comment]
Hi

the cfbundleidentifier for that specific panel is :

com.websense.endpoint.preference

I attached the whole info.plit file in case any other info is needed
Best Regards

*Adrian Guliciuc*
*Senior IT Technical Support, **IT **Department*

The content of this communication is classified as Softvision Confidential
and Proprietary Information

**Comment by csvjamfteam** [comment]
thank you for your assistance!
Best Regards

*Adrian Guliciuc*
*Senior IT Technical Support, **IT **Department*

The content of this communication is classified as Softvision Confidential
and Proprietary Information
