### ISSUE TITLE
Disable Personalized advertising

### ISSUE THREAD

**Issue by liquidoshin** [ProfileCreator/ProfileManifests#527]
### Please provide the following information:

**App Name**: Disable Personalized advertising.

**App URL**: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjmhozEyoL2AhWRKH0KHTPKCBEQFnoECAQQAQ&url=https%3A%2F%2Fcsrc.nist.gov%2FCSRC%2Fmedia%2FProjects%2Fnational-vulnerability-database%2Fdocuments%2FCCE%2Fcce-macos_bigsur.xls&usg=AOvVaw0XRSWpBSHnn2PaYHrDBLzO

**App Profile Documentation URL**: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjmhozEyoL2AhWRKH0KHTPKCBEQFnoECAQQAQ&url=https%3A%2F%2Fcsrc.nist.gov%2FCSRC%2Fmedia%2FProjects%2Fnational-vulnerability-database%2Fdocuments%2FCCE%2Fcce-macos_bigsur.xls&usg=AOvVaw0XRSWpBSHnn2PaYHrDBLzO

**Payload / Domain**: *com.apple.AdLib:
    allowApplePersonalizedAdvertising: false

**Comment by relgit** [comment]
See #526 for discussion about this issue.
