### ISSUE TITLE
Microsoft Autoupdate - Defender rename/rebrand

### ISSUE THREAD

**Issue by nixtar** [ProfileCreator/ProfileManifests#531]
Microsoft has released an update for defender that renames the app from `/Application/Microsoft Defender ATP.app` to `/Application/Microsoft Defender.app`.

As a result the path in the Applications dictionary needs updating before MAU will work with the new app name.

I made a fork and removed all references to ATP here:
https://github.com/nixtar/ProfileManifests/commit/598431d7f2f533b11cf23a4c1804d24c4e803040

This works and I was going to send a PR but then thought that after this change any old clients our there that are still ATP branded would now be broken/no longer updated.
Possibly both the new and old app paths are required for full coverage.

I don't have a copy of the old client to test this however.

**Applicable Preference Documentation URL(s)**:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-whatsnew?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-updates?view=o365-worldwide#set-the-channel-name

**Comment by kevinmcox** [comment]
Do you know the version of Defender when the change was made? There are already some places in this manifest where different values get written depending on versions.

Also note, an app array in this profile is not required for MAU to update an app, it is just a holdover and backup.

MAU should detect the app and update it even without the profile.

**Comment by nixtar** [comment]
The change was done in 101.56.35 (20.121121.15635.0) https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-whatsnew?view=o365-worldwide#1015635-20121121156350

In our environment where we have the App list configured, MAU was not detecting any updates to defender until I changed it to `/Application/Microsoft Defender.app`.

We implement the app list originally as we had issues with MAU not detecting apps when they had not been run once. I guess that's not applicable for defender due to the nature of the app.

I'll test removing defender from the app array and see if MAU finds it after a fresh install.

**Comment by kevinmcox** [comment]
That was the original reason for the app array. The Office apps have worked around the "needing to launch" problem as part of the installers.

I'm not sure if Defender has done the same, I guess I assumed it would have been launched at least once though.

(Disclaimer, we don't run Defender.)

In your opinion, will most people update to this new, changed path, version of Defender fairly quickly?

**Comment by nixtar** [comment]
Okay I've tested not having defender defined in the app array and MAU then stopped showing the Defender client.
I assume if you have any app defined then MAU stops trying to auto detect apps?

Yes the defender client is launched automatically after install.

If the issue with Office apps has been resolved then I may need to test not using the app array at all.

The official deployment guide recommends configuring MAU with a profile that enables automatic downloading and installing of updates. So assuming everyone follows those recommendations and doesn't use a custom manifest server to gate updates, yes I would think most people would be keeping up to date with the latest version of the client.

I have now also tested putting both the new and old defender app paths in the app array.
EG:
```xml
<key>Applications</key>
<dict>
	<key>/Applications/Microsoft Defender.app</key>
	<dict>
		<key>Application ID</key>
		<string>WDAV00</string>
		<key>LCID</key>
		<integer>1033</integer>
	</dict>
	<key>/Applications/Microsoft Defender ATP.app</key>
	<dict>
		<key>Application ID</key>
		<string>WDAV00</string>
		<key>LCID</key>
		<integer>1033</integer>
	</dict>
</dict>
```

However I am still unable to track down an old "ATP" installer to confirm the transition works.

**Comment by nixtar** [comment]
I managed to track down a copy of 101.54.16 when it was still `101.54.16`!

I can confirm that having both `/Applications/Microsoft Defender ATP.app` and `/Applications/Microsoft Defender.app` defined in the app array kind of works..
MAU detects the "ATP" app, but post update it does not detect the "Defender" app until MAU is closed and reopened.
This is not the end of the world as background checks should affectively be new instances anyway.

I'm not very fluent ProfileManifests are put together. Is it possible to have both apps defined with a single WDAV00 option?
Or should these be treated as separate entries? If so then perhaps we need to refactor the pfm_name's to reflect what app they are in reference to?

Happy to have a crack and send a PR.

**Comment by kevinmcox** [comment]
> I assume if you have any app defined then MAU stops trying to auto detect apps?

I wouldn't think so, but honestly have never tested it and just push an app array out of habit.

> If the issue with Office apps has been resolved then I may need to test not using the app array at all.

I'd be curious if that works for Defender.

> The official deployment guide recommends configuring MAU with a profile that enables automatic downloading and installing of updates. So assuming everyone follows those recommendations and doesn't use a custom manifest server to gate updates, yes I would think most people would be keeping up to date with the latest version of the client.

I noticed that MS doesn't include the app array in their example config profiles for Defender at all, so it shouldn't be needed but your earlier question about a partial app array could factor in.

**Comment by kevinmcox** [comment]
> I'm not very fluent ProfileManifests are put together. Is it possible to have both apps defined with a single WDAV00 option? Or should these be treated as separate entries? If so then perhaps we need to refactor the pfm_name's to reflect what app they are in reference to?

MAU will need them seperate, since the app path is the key that defines everything below it (AID and LCID).

My personal opinion is that we just update the manifest to reflect the "current" release of Defender (and the new path). We could make a note that the path changed in version 101.56.35 on X date. Any chance you know the date that version released, it isn't in the release notes.

What do you think @apizz ?

**Comment by nixtar** [comment]
> I wouldn't think so, but honestly have never tested it and just push an app array out of habit.

I've now tested deploying an app array that only contains Microsoft Word.app and can confirm that MAU now only detects word.
If I deploy no app list then it successfully detects all the Office apps and both new/old Defender versions.
I assume in MAUs code it generates its own app array only when the user/system has not supplied its own app array.

> My personal opinion is that we just update the manifest to reflect the "current" release of Defender (and the new path). We could make a note that the path changed in version 101.56.35 on X date. Any chance you know the date that version released, it isn't in the release notes.

Hmm, if this setting was applied to defender then I think that would be fine. But as its a MAU setting and with the current state of MAU it appears that having both is valid config.

It might be better to discuss this over at https://github.com/pbowden-msft/Payloads to get Pauls opinion? Any change like this should also be reflected over there also.

**Comment by kevinmcox** [comment]
Interesting results, thanks for testing that scenario.

Let me reach out to Paul and ask him to weigh in here.

**Comment by kevinmcox** [comment]
The real unexpected part of that behavior to me is that it means if an admin wants to use the app array to define a deadline for a single specific app, they must add every other app into the array to make sure MAU continues to update them without a deadline.

**Comment by nixtar** [comment]
Thanks Kevin, I appreciate you and all the work you do in the macadmins space. 😃

Let me know if you want me to do any testing on my end.
I also have access to MS premier support so if you can't get onto Paul through the usual channels then I can try the "official" path. 😉

**Comment by nixtar** [comment]
> The real unexpected part of that behavior to me is that it means if an admin wants to use the app array to define a deadline for a single specific app, they must add every other app into the array to make sure MAU continues to update them without a deadline.

Doubling back on this. The deadlines are defined under the "UpdateDeadline.ApplicationsForcedUpdateSchedule" array not the Applications array.
I leave the UpdateDeadline.ApplicationsForcedUpdateSchedule array out of my profile.

**Comment by kevinmcox** [comment]
Specific date deadlines yes, but individual app `UpdateDeadline.DaysBeforeForcedQuit` deadlines go in the app array we are discussing.

**Comment by apizz** [comment]
Just checking in on this conversation.  It's been a busy start to the year.

**Comment by cashxx** [comment]
Just ran across Defender not updating here.  Pushed it out in around February I believe. iMazing and ProfileCreator create the path of /Applications/Microsoft Defender ATP.app and was the issue for me.   I manually edited the mobileconfig and took out ATP and just made it /Applications/Microsoft Defender.app and pushed the new config and it started to show up and update in MAU.

**Comment by kevinmcox** [comment]
Thanks for the bump @cashxx , we need to fix that.

**Comment by cashxx** [comment]
Any updates on this, just came across this again. I made changes using iMazing and forgot to manually edit the file to take out ATP and clients haven't been getting updates for Defender.  Been almost a year for what seems like a simple fix of just changing the path from /Applications/Microsoft Defender ATP.app  to   /Applications/Microsoft Defender.app.  Everyone should be using the new Defender by now and would agree to just switch it to the latest.

**Comment by systemswizard** [comment]
Agreed on everyone using the new defender, the old one has aged out as each build has a time bomb on them to stop people from trying to hold back for X, Y, Z, reason

@nixtar can you do a PR of your change?

**Comment by maximvelichko** [comment]
@nixtar , any plan to fix it (@colorenz 's commit would do it)?
There is no reason to keep /Applications/Microsoft Defender ATP.app at all, the last version that used it is gone long time ago, a user just cannot install it anymore. Users who install the distributed profile get into a misconfigured system, where Defender is never updated.

(Speaking on behalf of Microsoft Defender for macOS team :-))

**Comment by nixtar** [comment]
> @nixtar , any plan to fix it (@colorenz 's commit would do it)? There is no reason to keep /Applications/Microsoft Defender ATP.app at all, the last version that used it is gone long time ago, a user just cannot install it anymore. Users who install the distributed profile get into a misconfigured system, where Defender is never updated.
> 
> (Speaking on behalf of Microsoft Defender for macOS team :-))

Agreed, by now it's not worth supporting the migration in these manifests.
