### ISSUE TITLE
Rename Google Drive and add missing settings

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#559]
`com.google.drivefs.settings` has a new name, new icon and new settings.

https://support.google.com/a/answer/7644837?hl=en

I'm working on this today.

**Comment by apizz** [comment]
This already merged.  If next time you say "Closes #<issue_number>" it should auto close

**Comment by kevinmcox** [comment]
Thanks, I forgot to cleanup!
