### ISSUE TITLE
Getting Username/Password in a profile

### ISSUE THREAD

**Issue by virus2016** [ProfileCreator/ProfileManifests#56]
Hi there, 

I love this app but maybe I have missed something. How do I use the Username and Password for example in Mail? It needs to read {{username}}@domain.com.

Thanks!

**Comment by erikberglund** [comment]
Tha varable format like that is done by the MDM you are using to install it, and different MDMs have different variable names and formats so you need to look at the mdms documentation.

**Comment by virus2016** [comment]
Thanks very much for the answer. We are looking at microMDM so will ask those guys what we can do there.
