### ISSUE TITLE
com.github.macadmins.Nudge.plist huge update v1.1.0 and up

### ISSUE THREAD

**Issue by epochvn** [ProfileCreator/ProfileManifests#561]
### Please provide the following information:

**Name of App / Payload**: *com.github.macadmins.Nudge.plist*

**Preference key(s) to be added / updated**: 
***User Experience*** - https://github.com/macadmins/nudge/wiki/userExperience
`allowGracePeriods`, `allowUserQuitDeferrals`, `gracePeriodInstallDelay`, `gracePeriodLaunchDelay`, `gracePeriodPath`, `showDeferralCount`
***User Interface*** - https://github.com/macadmins/nudge/wiki/userInterface
`singleQuitButton`
***OS Version Requirements*** - https://github.com/macadmins/nudge/wiki/osVersionRequirements
`actionButtonPath`, `targetedOSVersions` is now deprecated, `targetedOSVersionsRule`
***Optional Features*** - https://github.com/macadmins/nudge/wiki/optionalFeatures
`acceptableApplicationBundleIDs`, `acceptableAssertionUsage`, `acceptableAssertionApplicationNames`, `acceptableCameraUsage`, `acceptableScreenSharingUsage`, `aggressiveUserExperience`, `aggressiveUserFullScreenExperience`, `asynchronousSoftwareUpdate`, `attemptToFetchMajorUpgrade`, `attemptToBlockApplicationLaunches`, `blockedApplicationBundleIDs`, `terminateApplicationsOnLaunch`

**Applicable Preference Documentation URL(s)**:
https://github.com/macadmins/nudge/wiki/v1.1.0-features
https://github.com/macadmins/nudge/wiki/userExperience
https://github.com/macadmins/nudge/wiki/userInterface
https://github.com/macadmins/nudge/wiki/osVersionRequirements
https://github.com/macadmins/nudge/wiki/optionalFeatures

**Comment by relgit** [comment]
@DigiYann is preparing a PR that would address this.
