### ISSUE TITLE
Add to Google Chrome Manifest for RelaunchNotification

### ISSUE THREAD

**Issue by cashxx** [ProfileCreator/ProfileManifests#573]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*
com.google.Chrome

**Preference key(s) to be added / updated**: *ex. `AppUpdateURL`, `Bookmarks`, etc.*
RelaunchNotification
RelaunchNotificationPeriod
RelaunchWindow

**Applicable Preference Documentation URL(s)**:
https://support.google.com/chrome/a/answer/7679871?hl=en#zippy=%2Cmac
https://www.alansiu.net/2019/11/24/forcing-updates-to-google-chrome-using-chrome-preferences-a-chrome-profile/

**Comment by kevinmcox** [comment]
It looks like the first two are already in the Chrome profile:
https://github.com/ProfileCreator/ProfileManifests/blob/master/Manifests/ManagedPreferencesApplications/com.google.Chrome.plist#L6551
https://github.com/ProfileCreator/ProfileManifests/blob/master/Manifests/ManagedPreferencesApplications/com.google.Chrome.plist#L6581

**Comment by cashxx** [comment]
Sorry! You are correct! I looked numerous times today in ProfileCreator and iMazing Profile Editor and couldn't find it anywhere. Looking again here and found the two about 3/4 down under Misc. tab!
