### ISSUE TITLE
Apple Freeform

### ISSUE THREAD

**Issue by kevinmcox** [ProfileCreator/ProfileManifests#591]
### Please provide the following information:

**App Name**:
Freeform

**App URL**:
https://www.apple.com/newsroom/2022/12/apple-launches-freeform-a-powerful-new-app-designed-for-creative-collaboration/

**App Profile Documentation URL**:
N/A

**Payload / Domain**:
com.apple.freeform

@wegotoeleven shared a key on the MacAdmins Slack that will disable the prompt to sign into iCloud when Freeform is launched:

```
<key>CRLConnectICloudDialogShown</key>
<integer>13001000</integer>
```

**Comment by apizz** [comment]
Oh hey I know that guy @wegotoeleven 😄

**Comment by wegotoeleven** [comment]
The value `13001000` is specific for macOS 13.1 (i.e teh value that is set on macOS 13.2 when the iCloud pop-up is cancelled is `1300200`. However, the value `99999999` works for both 13.1 and 13.2. It is assumed this will also work for macOS 13.3+.
