### ISSUE TITLE
Disable Install of Microsoft Defender

### ISSUE THREAD

**Issue by cashxx** [ProfileCreator/ProfileManifests#632]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*
com.microsoft.office

**Preference key(s) to be added / updated**: *ex. `AppUpdateURL`, `Bookmarks`, etc.*
InstallDefender
Boolean true/false

**Applicable Preference Documentation URL(s)**:
https://learn.microsoft.com/en-us/deployoffice/mac/preferences-office#app-installation

**Comment by kevinmcox** [comment]
Addressed by https://github.com/ProfileCreator/ProfileManifests/pull/630
