### ISSUE TITLE
Tailscale standalone: HiddenNetworkDevices

### ISSUE THREAD

**Issue by swy** [ProfileCreator/ProfileManifests#653]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*
io.tailscale.ipn.macsys

**Preference key(s) needing fixing**: *ex. `AppUpdateURL`*
HiddenNetworkDevices

**Description of problem(s) / error(s) with listed key(s)**: *ex. When `X` preference is configured, it does not *
.mobileconfig saved out lists key as Hidden network devices

**Description of expected behavior**:
Proper name of key is HiddenNetworkDevices 

**Applicable Documentation URL(s)**: *If applicable ...*

**How are you testing / deploying your profile?**: *ex. manual profile install, MDM, etc.*
MDM

**Comment by apizz** [comment]
Resolved in #654
