### ISSUE TITLE
Fix Content Filter Payload: Doesn't Allow Blocking of Websites

### ISSUE THREAD

**Issue by deanocko** [ProfileCreator/ProfileManifests#675]
Hi! Thanks for the awesome app! iMazing is great.

Firstly, apologies if this isn't in the correct format etc.

Flagging a bug. In the images shown below I have the same configuration profile opened both in apple configurator (AC) and in iMazing profile editor (IPE). You can see that the Content Filter payload within AC allows me to allow and block websites. Key functionality. The IPE editor doesn't let you do this!

I've scrambled the links as they are just an example.

Please fix. Thanks!

![Screenshot 2024-05-26 at 1 46 19 PM](https://github.com/ProfileCreator/ProfileManifests/assets/37322602/7a33d258-74dd-429d-bccf-f0ae7f5e6bd7)

![Screenshot 2024-05-26 at 1 46 43 PM](https://github.com/ProfileCreator/ProfileManifests/assets/37322602/d8c7a942-7179-4f2b-aa6c-8db1d0a1db91)

**Comment by relgit** [comment]
Thanks for reporting this @deanocko.

Looks like our conditions over-exclude this property when automatic filtering is on.
