### ISSUE TITLE
Munki IgnoreMiddleware

### ISSUE THREAD

**Issue by patgmac** [ProfileCreator/ProfileManifests#693]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*
Munki

**Preference key(s) to be added / updated**: *ex. `AppUpdateURL`, `Bookmarks`, etc.*
IgnoreMiddleware

**Applicable Preference Documentation URL(s)**:

https://github.com/munki/munki/wiki/Preferences

**Comment by kevinmcox** [comment]
> relgit self-assigned this 4 hours ago

Haha, looks like we had the same idea on how to spend the holiday @relgit.

**Comment by relgit** [comment]
I can assure you I had no such plans 😄

I'm just saving you from doing the same work I already did on our fork which will come after our Aug PR is merged.
