### ISSUE TITLE
Support `BraveAIChatEnabled` setting for Brave Browser

### ISSUE THREAD

**Issue by securitygeneration** [ProfileCreator/ProfileManifests#694]
### Please provide the following information:

**Name of App / Payload**: *ex. Firefox OR org.mozilla.firefox*

`com.brave.Browser`

**Preference key(s) to be added / updated**: *ex. `AppUpdateURL`, `Bookmarks`, etc.*

`BraveAIChatEnabled`

**Applicable Preference Documentation URL(s)**:

https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy

Options `0` or `1` (default `1`)

**Comment by securitygeneration** [comment]
@relgit looks like this isn't working. This attribute expects an actual `true/false` boolean. Setting an integer results in an error

<img width="1464" alt="image" src="https://github.com/user-attachments/assets/f9c9c456-09f3-4e84-98c9-2a232bdd1575">

**Comment by relgit** [comment]
@securitygeneration have you tested it to work with an actual boolean?

**Comment by securitygeneration** [comment]
I confess I don't know how, so I haven't tried. Can look into it by copying a Boolean from another attribute if you want.

**Comment by relgit** [comment]
It's quite easy actually, assuming that your profile is not signed.

Open the profile in a text editor, and locate the `BraveAIChatEnabled` property key. Below the key you'll find the value, which for now will probably be `<integer>0</integer>`. Change the value to `<false/>` and save the profile. Then, install the modified profile on your machine and check again in the policy console.

**Comment by securitygeneration** [comment]
Ohh, you mean in the final profile. Of course how dumb of me. I thought you meant in the ProfileCreator files directly. 

Yes, changing it to false works. In fact there are three attributes (at least, as far as I could find) currently set to `0|1` by ProfileCreator/iMazing which error and need to be changed to Boolean:
* BraveAIChatEnabled
* BraveVPNDisabled; and
* TorDisabled

**Comment by securitygeneration** [comment]
@relgit it seems I can't reopen this ticket, could you update the manifest to use a Boolean for these keys?

**Comment by relgit** [comment]
Thanks for testing @securitygeneration; What an interesting catch.

This got me questioning the whole Brave documentation page, and luckily the browser is open sourced so we can examine the code where these preferences are actually defined:
https://github.com/brave/brave-core/blob/master/browser/policy/brave_simple_policy_map.h

And what do you know? The documentation page is really messed up because there is not a single integer in sight.

So we should definitely update the manifest, but to keep things clean I'll open a new issue.

**Comment by securitygeneration** [comment]
Maybe I'll try reporting the documentation flaws to the Brave project

**Comment by relgit** [comment]
That would be helpful.
