### ISSUE TITLE
Update Microsoft Office Manifest

### ISSUE THREAD

**Issue by bp88** [ProfileCreator/ProfileManifests#78]
As of this writing, there have been about 50+ preference keys added for Office-related apps. The Google Sheet containing these preference keys are located here: https://docs.google.com/spreadsheets/d/1ESX5td0y0OP3jdzZ-C2SItm-TUi-iA_bcHCBvaoCumw/edit#gid=0

I've intentionally left the preference keys at the bottom of the sheet starting at line 114 (at the time of this writing) so that it would be easier to see the new keys that have been added. You'll know because there's an empty white line between the sorted entries and the new entries that haven't been sorted. It's possible there may be even a few additional keys I've missed related to MAU and other Office apps that aren't part of the main suite. In any case, feel free to let me know if you've got any questions. Probably easiest to reach out to me on Slack: @bp

Also, let me know if you think it'd make sense to add a column specifically for ProfileCreator so we can mark off which keys have been added to the manifests.

**Comment by kevinmcox** [comment]
This was taken care of with #124 and #126.
